# Done to increase the memory available to gradle.yml.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
fabric_loom=1.14-SNAPSHOT
# Mod Properties
mod_version=1.4.1
maven_group=com.quantumgarbage
archives_base_name=screenshotsettings
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.141.0+1.21.11
cloth_config=21.11.153
modmenu=17.0.0-beta.1
yacl=3.8.1+1.21.11-fabric
iris=1.10.4+1.21.11-fabric
sodium=mc1.21.11-0.8.2-fabric